// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKlYBTvgX5OvqsDtkkpoKHoxP9VXOY5-A',
    appId: '1:72205811398:web:b0e6434f8a6d8cb4e421c7',
    messagingSenderId: '72205811398',
    projectId: 'medicare-67e1f',
    authDomain: 'medicare-67e1f.firebaseapp.com',
    storageBucket: 'medicare-67e1f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLfxeWpyLO4D6b_7BBL-D1ZY4MwvmE4c',
    appId: '1:72205811398:android:86db16ee5cbea3b1e421c7',
    messagingSenderId: '72205811398',
    projectId: 'medicare-67e1f',
    storageBucket: 'medicare-67e1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjVjJidSTZj2XbMALoElcB8ARQnskF3c',
    appId: '1:72205811398:ios:9bfa2e76b9e0614de421c7',
    messagingSenderId: '72205811398',
    projectId: 'medicare-67e1f',
    storageBucket: 'medicare-67e1f.firebasestorage.app',
    iosBundleId: 'com.example.mediclic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjVjJidSTZj2XbMALoElcB8ARQnskF3c',
    appId: '1:72205811398:ios:9bfa2e76b9e0614de421c7',
    messagingSenderId: '72205811398',
    projectId: 'medicare-67e1f',
    storageBucket: 'medicare-67e1f.firebasestorage.app',
    iosBundleId: 'com.example.mediclic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKlYBTvgX5OvqsDtkkpoKHoxP9VXOY5-A',
    appId: '1:72205811398:web:686e5ba221c07e51e421c7',
    messagingSenderId: '72205811398',
    projectId: 'medicare-67e1f',
    authDomain: 'medicare-67e1f.firebaseapp.com',
    storageBucket: 'medicare-67e1f.firebasestorage.app',
  );
}
